# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 11:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0003_auto_20170814_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='client_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usermanage.Clients'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clients',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 14, 17, 6, 29, 979079)),
        ),
        migrations.AlterField(
            model_name='clients',
            name='modified_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 14, 17, 6, 29, 979148)),
        ),
        migrations.AlterField(
            model_name='countries',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 14, 17, 6, 29, 986262)),
        ),
        migrations.AlterField(
            model_name='countries',
            name='modified_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 14, 17, 6, 29, 986310)),
        ),
    ]
