# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 11:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0004_auto_20170814_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='client_id',
            new_name='clients',
        ),
        migrations.AlterField(
            model_name='clients',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 14, 17, 7, 41, 592777)),
        ),
        migrations.AlterField(
            model_name='clients',
            name='modified_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 14, 17, 7, 41, 592847)),
        ),
        migrations.AlterField(
            model_name='countries',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 14, 17, 7, 41, 599730)),
        ),
        migrations.AlterField(
            model_name='countries',
            name='modified_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 14, 17, 7, 41, 599785)),
        ),
    ]
