# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 12:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0005_auto_20170814_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywords',
            name='source_type',
            field=models.CharField(default='facebook', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keywords',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 14, 18, 2, 28, 172008)),
        ),
        migrations.AlterField(
            model_name='clients',
            name='modified_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 14, 18, 2, 28, 172115)),
        ),
        migrations.AlterField(
            model_name='countries',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 14, 18, 2, 28, 184527)),
        ),
        migrations.AlterField(
            model_name='countries',
            name='modified_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 14, 18, 2, 28, 184614)),
        ),
    ]
