# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 12:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0010_auto_20170816_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 16, 18, 1, 7, 506129)),
        ),
        migrations.AlterField(
            model_name='clients',
            name='modified_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 16, 18, 1, 7, 506206)),
        ),
        migrations.AlterField(
            model_name='countries',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 16, 18, 1, 7, 512126)),
        ),
        migrations.AlterField(
            model_name='countries',
            name='modified_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 16, 18, 1, 7, 512185)),
        ),
        migrations.AlterField(
            model_name='keywords',
            name='clients',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usermanage.Clients'),
        ),
        migrations.AlterField(
            model_name='keywords',
            name='source_type',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
