# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 13:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0011_auto_20170816_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 16, 19, 11, 4, 765195)),
        ),
        migrations.AlterField(
            model_name='clients',
            name='modified_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 16, 19, 11, 4, 765249)),
        ),
        migrations.AlterField(
            model_name='countries',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 16, 19, 11, 4, 771078)),
        ),
        migrations.AlterField(
            model_name='countries',
            name='modified_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 16, 19, 11, 4, 771134)),
        ),
        migrations.AlterField(
            model_name='keywords',
            name='status',
            field=models.IntegerField(default=True),
        ),
    ]
