# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 11:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0012_auto_20170816_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name of the book')),
                ('author_name', models.CharField(max_length=50, verbose_name='the name of the author')),
            ],
        ),
        migrations.AlterField(
            model_name='clients',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 17, 16, 40, 40, 540852)),
        ),
        migrations.AlterField(
            model_name='clients',
            name='modified_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 17, 16, 40, 40, 541023)),
        ),
        migrations.AlterField(
            model_name='countries',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 17, 16, 40, 40, 548274)),
        ),
        migrations.AlterField(
            model_name='countries',
            name='modified_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 17, 16, 40, 40, 548323)),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='start_date',
            field=models.DateField(),
        ),
    ]
