"""
    Rss Links for some News papers
"""

EENADULINKS = [
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=16&Main=2',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=13&Main=2',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=14&Main=2',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=15&Main=2',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=17&Main=3',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=18&Main=4',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=19&Main=4',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=20&Main=5',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=21&Main=5',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=22&Main=5',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=23&Main=6',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=24&Main=6',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=25&Main=6',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=26&Main=6',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=27&Main=6',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=28&Main=6',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=29&Main=6',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=30&Main=6',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=32&Main=7',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=33&Main=8',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=34&Main=8',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=35&Main=8',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=36&Main=8',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=37&Main=8',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=43&Main=9',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=137&Main=1&IsState=1',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=140&Main=1&IsState=1',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=143&Main=1&IsState=1',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=146&Main=1&IsState=1',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=156&Main=1&IsState=1',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=168&Main=1&IsState=1',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=170&Main=1&IsState=1',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=172&Main=1&IsState=1',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=174&Main=1&IsState=1',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=176&Main=1&IsState=1',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=182&Main=1&IsState=1',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=190&Main=1&IsState=1',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=196&Main=1&IsState=1',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=212&Main=3&IsState=1',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=203&Main=3&IsState=1',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=150&Main=3&IsState=1',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=152&Main=3&IsState=1',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=154&Main=3&IsState=1',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=163&Main=3&IsState=1',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=178&Main=3&IsState=1',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=180&Main=3&IsState=1',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=194&Main=3&IsState=1',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=192&Main=3&IsState=1',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=134&Main=4&IsState=1',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=158&Main=4&IsState=1',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=161&Main=4&IsState=1',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=206&Main=4&IsState=1',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=208&Main=4&IsState=1',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=184&Main=4&IsState=1',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=187&Main=4&IsState=1',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=201&Main=2&IsState=1',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=210&Main=2&IsState=1',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=214&Main=2&IsState=1',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=148&Main=2&IsState=1',
'http://www.eenaduindia.com/RSS/SectionRssFeed.aspx?Id=165&Main=2&IsState=1']

TMILINKS = [
'http://timesofindia.indiatimes.com/rssfeedstopstories.cms',
'http://timesofindia.indiatimes.com/rssfeeds/1221656.cms',
'http://timesofindia.indiatimes.com/rssfeeds/-2128936835.cms',
'http://timesofindia.indiatimes.com/rssfeeds/296589292.cms',
'http://timesofindia.indiatimes.com/rssfeeds/7098551.cms',
'http://timesofindia.indiatimes.com/rssfeeds/1898055.cms',
'http://timesofindia.indiatimes.com/rssfeeds/4719161.cms',
'http://timesofindia.indiatimes.com/rssfeeds/4719148.cms',
'http://timesofindia.indiatimes.com/rssfeeds/-2128672765.cms',
'http://timesofindia.indiatimes.com/rssfeeds/5880659.cms',
'http://timesofindia.indiatimes.com/rssfeedmostread.cms',
'http://timesofindia.indiatimes.com/rssfeedmostemailed.cms',
'http://timesofindia.indiatimes.com/rssfeedmostcommented.cms',
'http://timesofindia.indiatimes.com/rssfeeds/-2128838597.cms',
'http://timesofindia.indiatimes.com/rssfeeds/-2128839596.cms',
'http://timesofindia.indiatimes.com/rssfeeds/-2128833038.cms',
'http://timesofindia.indiatimes.com/rssfeeds/-2128816011.cms',
'http://timesofindia.indiatimes.com/rssfeeds/2950623.cms',
'http://timesofindia.indiatimes.com/rssfeeds/-2128821153.cms',
'http://timesofindia.indiatimes.com/rssfeeds/3947060.cms',
'http://timesofindia.indiatimes.com/rssfeeds/4118235.cms',
'http://timesofindia.indiatimes.com/rssfeeds/7503091.cms',
'http://timesofindia.indiatimes.com/rssfeeds/6547154.cms',
'http://timesofindia.indiatimes.com/rssfeeds/4118215.cms',
'http://timesofindia.indiatimes.com/rssfeeds/3942695.cms',
'http://timesofindia.indiatimes.com/rssfeeds/3947067.cms',
'http://timesofindia.indiatimes.com/rssfeeds/-2128830821.cms',
'http://timesofindia.indiatimes.com/rssfeeds/3947051.cms',
'http://timesofindia.indiatimes.com/rssfeeds/3942690.cms',
'http://timesofindia.indiatimes.com/rssfeeds/3942693.cms',
'http://timesofindia.indiatimes.com/rssfeeds/8021716.cms',
'http://timesofindia.indiatimes.com/rssfeeds/-2128821991.cms',
'http://timesofindia.indiatimes.com/rssfeeds/3012535.cms',
'http://timesofindia.indiatimes.com/rssfeeds/-2128816762.cms',
'http://timesofindia.indiatimes.com/rssfeeds/-2128819658.cms',
'http://timesofindia.indiatimes.com/rssfeeds/-2128817995.cms',
'http://timesofindia.indiatimes.com/rssfeeds/3012544.cms',
'http://timesofindia.indiatimes.com/rssfeeds/442002.cms',
'http://timesofindia.indiatimes.com/rssfeeds/3942663.cms',
'http://timesofindia.indiatimes.com/rssfeeds/4118245.cms',
'http://timesofindia.indiatimes.com/rssfeeds/3942660.cms',
'http://timesofindia.indiatimes.com/rssfeeds/4118245.cms',
'http://timesofindia.indiatimes.com/rssfeeds/3942660.cms',
'http://timesofindia.indiatimes.com/rssfeeds/3942666.cms',
'http://timesofindia.indiatimes.com/rssfeeds/3947071.cms',
'http://timesofindia.indiatimes.com/rssfeeds/30359486.cms',
'http://timesofindia.indiatimes.com/rssfeeds/7098551.cms',
'http://timesofindia.indiatimes.com/rssfeeds/30359534.cms',
'http://timesofindia.indiatimes.com/rssfeeds/3907412.cms',
'http://timesofindia.indiatimes.com/rssfeeds/2177298.cms',
'http://timesofindia.indiatimes.com/rssfeeds/1898274.cms',
'http://timesofindia.indiatimes.com/rssfeeds/1898184.cms',
'http://timesofindia.indiatimes.com/rssfeeds/1898272.cms',
'http://timesofindia.indiatimes.com/rssfeeds/671314.cms',
'http://timesofindia.indiatimes.com/rssfeeds/2178430.cms',
'http://blogs.timesofindia.indiatimes.com/feed/defaultrss',
]

APHERALDLINKS = [
'http://www.apherald.com/rss/en/',
'http://www.apherald.com/rss/eng',
'http://www.apherald.com/rss/politics/english',
'http://www.apherald.com/rss/politics',
'http://www.apherald.com/rss/worldpolitics',
'http://www.apherald.com/rss/indiapolitics',
'http://www.apherald.com/rss/tamilnadupolitics',
'http://www.apherald.com/rss/telanganapolitics',
'http://www.apherald.com/rss/andhrapolitics',
'http://www.apherald.com/rss/business',
'http://www.apherald.com/rss/technology',
'http://www.apherald.com/rss/sports',
'http://www.apherald.com/rss/sportstel',
'http://www.apherald.com/rss/health',
'http://www.apherald.com/rss/spirituality',
'http://www.apherald.com/rss/women',
'http://www.apherald.com/rss/education',
'http://www.apherald.com/rss/lifestyle',
'http://www.apherald.com/rss/nri',
'http://www.apherald.com/rss/Gossips_English',
'http://www.apherald.com/rss/Analysis_English',
]

HINDULINKS = [
'http://www.thehindu.com/news/national/?service=rss',
'http://www.thehindu.com/news/international/?service=rss',
'http://www.thehindu.com/news/states/?service=rss',
'http://www.thehindu.com/news/cities/?service=rss',
'http://www.thehindu.com/business/Economy/?service=rss',
'http://www.thehindu.com/business/budget/?service=rss']

ONEINDIALINKS = [
'http://www.oneindia.com/rss/news-business-fb.xml',
'http://www.oneindia.com/rss/news-international-fb.xml',
'http://www.oneindia.com/rss/news-india-fb.xml',
'http://www.oneindia.com/rss/news-sports-fb.xml',
'http://www.oneindia.com/rss/feature-fb.xml']

from urllib2 import Request,urlopen

if __name__ == '__main__':

    print len(EENADULINKS)+len(APHERALDLINKS)+len(HINDULINKS)+len(ONEINDIALINKS) + len(TMILINKS)